/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as InicioRouteImport } from './routes/inicio'
import { Route as DadosRouteImport } from './routes/dados'
import { Route as CarteiraIdentidadeRouteImport } from './routes/carteira-identidade'
import { Route as CarteiraRouteImport } from './routes/carteira'
import { Route as IndexRouteImport } from './routes/index'

const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const InicioRoute = InicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => rootRouteImport,
} as any)
const DadosRoute = DadosRouteImport.update({
  id: '/dados',
  path: '/dados',
  getParentRoute: () => rootRouteImport,
} as any)
const CarteiraIdentidadeRoute = CarteiraIdentidadeRouteImport.update({
  id: '/carteira-identidade',
  path: '/carteira-identidade',
  getParentRoute: () => rootRouteImport,
} as any)
const CarteiraRoute = CarteiraRouteImport.update({
  id: '/carteira',
  path: '/carteira',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/carteira': typeof CarteiraRoute
  '/carteira-identidade': typeof CarteiraIdentidadeRoute
  '/dados': typeof DadosRoute
  '/inicio': typeof InicioRoute
  '/menu': typeof MenuRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/carteira': typeof CarteiraRoute
  '/carteira-identidade': typeof CarteiraIdentidadeRoute
  '/dados': typeof DadosRoute
  '/inicio': typeof InicioRoute
  '/menu': typeof MenuRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/carteira': typeof CarteiraRoute
  '/carteira-identidade': typeof CarteiraIdentidadeRoute
  '/dados': typeof DadosRoute
  '/inicio': typeof InicioRoute
  '/menu': typeof MenuRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/carteira'
    | '/carteira-identidade'
    | '/dados'
    | '/inicio'
    | '/menu'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/carteira'
    | '/carteira-identidade'
    | '/dados'
    | '/inicio'
    | '/menu'
  id:
    | '__root__'
    | '/'
    | '/carteira'
    | '/carteira-identidade'
    | '/dados'
    | '/inicio'
    | '/menu'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CarteiraRoute: typeof CarteiraRoute
  CarteiraIdentidadeRoute: typeof CarteiraIdentidadeRoute
  DadosRoute: typeof DadosRoute
  InicioRoute: typeof InicioRoute
  MenuRoute: typeof MenuRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inicio': {
      id: '/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof InicioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dados': {
      id: '/dados'
      path: '/dados'
      fullPath: '/dados'
      preLoaderRoute: typeof DadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carteira-identidade': {
      id: '/carteira-identidade'
      path: '/carteira-identidade'
      fullPath: '/carteira-identidade'
      preLoaderRoute: typeof CarteiraIdentidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carteira': {
      id: '/carteira'
      path: '/carteira'
      fullPath: '/carteira'
      preLoaderRoute: typeof CarteiraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CarteiraRoute: CarteiraRoute,
  CarteiraIdentidadeRoute: CarteiraIdentidadeRoute,
  DadosRoute: DadosRoute,
  InicioRoute: InicioRoute,
  MenuRoute: MenuRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
